# fly.toml app configuration file generated for cpme-notifier on 2025-07-23T20:40:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cpme-notifier'
primary_region = 'cdg'

[build]
  dockerfile = 'deploy/Dockerfile'

[env]
  POLL_INTERVAL = "60"  # Check every minute in production
  ENABLE_HEALTH_SERVER = "true"
  CPME_URL = "https://cpme.fyidigital.pt/arrendamento"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "10s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[restart]]
  policy = "always"
  processes = ["app"]
