app = "cpme-notifier"
primary_region = "mad"  # Madrid region (closest to Portugal)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  POLL_INTERVAL = "60"  # Check every minute in production
  ENABLE_HEALTH_SERVER = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Keep running continuously
  auto_start_machines = true

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "10s"

[processes]
  app = "python main.py"

[[mounts]]
  source = "cpme_data"
  destination = "/app/data"